apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-autodeploy-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-autodeploy-demo
  template:
    metadata:
      labels:
        app: platform-autodeploy-demo
    spec:
      containers:
        - name: web
          image: nginx:alpine
          ports:
            - containerPort: 80
